source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/db.sqlite3*"
  - "*/logs"
  - "*/cache"

sqlite_databases:
  - name: seerr
    path: /source/data/db/db.sqlite3

repositories:
  - path: /repository
    label: nas

archive_name_format: "seerr-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "seerr backup complete"
    message: "seerr backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "seerr backup FAILED"
    message: "seerr backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
