services:
  seerr:
    container_name: seerr
    image: seerr/seerr:v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
    environment:
      - TZ=America/Chicago
    volumes:
      - /home/jaw/data/seerr:/app/config
    networks:
      - traefik
      - media
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.rule=Host(`seerr.jaw.dev`)"
      - "traefik.http.routers.seerr.entrypoints=websecure"
      - "traefik.http.routers.seerr.middlewares=google-auth-user@file"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
networks:
  traefik:
    external: true
  media:
    external: true
