source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/sonarr.db*"
  - "*/logs.db*"
  - "*/asp"
  - "*/logs"
  - "*/Sentry"
  - "*.pid"

sqlite_databases:
  - name: sonarr
    path: /source/data/sonarr.db

repositories:
  - path: /repository
    label: sonarr

archive_name_format: "sonarr-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "sonarr backup complete"
    message: "sonarr backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "sonarr backup FAILED"
    message: "sonarr backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
