sqlite_databases:
  - name: bang
    path: /source/data/db.sqlite

repositories:
  - path: /repository
    label: bang

archive_name_format: "bang-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "bang db backup complete"
    message: "bang database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "bang db backup FAILED"
    message: "bang database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
