apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel
  namespace: network
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:kt+yUC0LaL2V+mvmJTfaLIZ5ydjuH+DNj+VFFlotu0aS+YOa4KGiEPUIJks0Fbjv6FpJpAsIco4c/z9uI2R+AOEvDMwqIyM6iHr16Szt6leKyvzDqldNiP8tahR7mNDmz/DRanoaYLkbO904k7OKPwqlGseLUX/hyEg8oIW6Q14DjCxLtMgMA5zxzXRaWkHnrg3/j9oxdJTgi3lBXGCmEvNMijTO,iv:NtlkV50r/AyaLqlxOhoB7cfV1hSC/qYrpTtvPmG3tGw=,tag:eE54aCC+4m0/w2EfWUnBGw==,type:str]
sops:
  age:
    - recipient: age1jcnrthtt049n6e2w2hpyq8r342q97r3ws44m0maty4dx527yvd7qyucfnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YnR1cTNEMEZKMzgxdzAz
        WmxjQVdHQVp4YlEvWVNSN3ByVXEzSnFIeTBnCi9YREI1M2hSM2ZzelEyRjJURENM
        dXZCM3VzQWxqOVJ3N0ZZSmpMVEVLOXcKLS0tIDc5dDNad0EzaUxsYkVVeFVuZjdy
        SDZVM3NYOXFVbm9OMU94TC9GeEtCMmsKEb/ukLhW8mKxv/5yyXgDctMs+3TrUxwF
        s9B8WfGilQ1wgo6hSBGFvvcSrGQ8KEFJ+Dn+1nE/xXudbgz+OcUR6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T06:24:26Z"
  mac: ENC[AES256_GCM,data:ziVCRN8XedE//AqIW2B+dTChNnZN7tHRusxEnrvqGvtWbUOGcMJVsbqpmxUB3Qe5Bb1/oO6RRbCApgablw6Ae2ePHdWs4klLn/ItD1bVtQ41dRXuFCVfpUU7weQwNUw+YaqLHR39AlRIeLyI4fYJR5iC1Us/rTsfhdwV95f4Dbg=,iv:hN4SNiOhCXq+CtuwFl0EI6mWnuSXWsuFr5txgyqds84=,tag:uzoctnYVTwlYYcsHcFHm9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
