apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel
  namespace: network
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:s/Ct6zqdvuawJaOtDJxRZNbKcnBDSySaelAff64QiP8FpyLOnBrIkm6a8kydT8iVnJSybQroJ+rm+dDxVMN0zzzzVejx0Erdv8q1jSPhI6yvFw/l2K/glm++QQ+0726GpOpK+rTUtUChENYjD9obYD53gPUjePrr2Jgoqrxog1a3cif5tp+0umI1TUEaEfoDbCK6MPqaM3MCO+e1Wxxcb3lhqViS9oXT63k7HoyWD7I=,iv:GlsMEwMh/2ODffDAwHq+Ho0i/zxJAv8mY1I6M97mZKk=,tag:Fn5vECGXJRbQ4/7wbqDGqQ==,type:str]
sops:
  age:
    - recipient: age1jcnrthtt049n6e2w2hpyq8r342q97r3ws44m0maty4dx527yvd7qyucfnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOG0xTnhDem1qeGRlU3F2
        ZGZxQVAvSnJwaWJSd3ZZS21ZeVJyVlZwUHlZCnlUNlpyWUJxUkN0RWxrRytZUUpj
        Y3l0ZUNIUG9WTGpuMVBiOHVTaDFUdWcKLS0tIEhhRDdJcnRjRDYrTHVuZ1BiWm94
        TGxKNmJqdllxNlJUZisrSW5TNlhIRFkK8E9PELuZsNUvXhwg9P7tjpXgf75WHUTh
        bLmgUljTF9NR5lSNIpgpvDMz4HEusfYyhkrf3Sx39phw/2L57eSyRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T18:01:01Z"
  mac: ENC[AES256_GCM,data:vWqCDjOxv3J2qEwQXU4zrFdgzdr3V63jaNdFgl+LhSDy9rjnieyrn58ny5ajfieZmgO11sBMdJ7glAvz8ZYIFCdMTq8LzH671O6ITLoObc5TiHVoxvQU3BOtT7iVivrrRsBrteCa/e8SBcqXgZ1/3NJCS5iXOcKi2jEy56spd6c=,iv:3N++H4DzmEDnMDEFplJTlMK45/gsPM29J1eo3/Uge3g=,tag:XqfTEJAJEgykkeAnr8Mgug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
