source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/Cache"
  - "*/Crash Reports"
  - "*/Logs"
  - "*/com.plexapp.plugins.library.db*"
  - "*/com.plexapp.plugins.library.blobs.db*"

sqlite_databases:
  - name: plex-library
    path: /source/data/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db
  - name: plex-blobs
    path: /source/data/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.blobs.db

repositories:
  - path: /repository
    label: nas

archive_name_format: "plex-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "plex backup complete"
    message: "plex backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "plex backup FAILED"
    message: "plex backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
