source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/db.sqlite3*"

sqlite_databases:
  - name: vaultwarden
    path: /source/data/db.sqlite3

repositories:
  - path: /repository
    label: vaultwarden

archive_name_format: "vaultwarden-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "vaultwarden backup complete"
    message: "vaultwarden backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "vaultwarden backup FAILED"
    message: "vaultwarden backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
