# doco-cd deployment configuration
# Docs: https://github.com/kimdre/doco-cd/wiki/Deploy-Settings

# Prometheus monitoring
name: prometheus
working_dir: infrastructure/prometheus
compose_files:
  - docker-compose.yml
remove_orphans: true
prune_images: true

---

# Homepage dashboard
name: homepage
working_dir: apps/homepage
compose_files:
  - docker-compose.yml
remove_orphans: true
prune_images: true

---

# Whoami test service
name: whoami
working_dir: apps/whoami
compose_files:
  - docker-compose.yml
remove_orphans: true
prune_images: true
