# doco-cd deployment configs
# NOTE: doco-cd and traefik are bootstrapped manually, not managed here

name: prometheus
working_dir: infrastructure/prometheus
compose_files:
  - docker-compose.yml

---

name: homepage
working_dir: apps/homepage
compose_files:
  - docker-compose.yml

---

name: whoami
working_dir: apps/whoami
compose_files:
  - docker-compose.yml
