source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/user.db*"
  - "*/cache.db*"

sqlite_databases:
  - name: ntfy-user
    path: /source/data/user.db
  - name: ntfy-cache
    path: /source/data/cache.db

repositories:
  - path: /repository
    label: ntfy

archive_name_format: "ntfy-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "ntfy backup complete"
    message: "ntfy backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "ntfy backup FAILED"
    message: "ntfy backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
