sqlite_databases:
  - name: notify
    path: /source/data/db.sqlite

repositories:
  - path: /repository
    label: notify

archive_name_format: "notify-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 30
keep_weekly: 12
keep_monthly: 12

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "notify db backup complete"
    message: "notify database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "notify db backup FAILED"
    message: "notify database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
