x-docker-cd:
  rolling_update: true

services:
  roadmap-for-bjj:
    image: ghcr.io/wajeht/roadmap-for-bjj:v1.0.0@sha256:5f45e21e9b9cab346ed3af1049bf71d6ddeda3d4fdba9377a3a1bfb92f0f3a1c
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:80/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roadmap-for-bjj.rule=Host(`bjj.jaw.dev`)"
      - "traefik.http.routers.roadmap-for-bjj.entrypoints=websecure"
      - "traefik.http.routers.roadmap-for-bjj.middlewares=rate-limit-global@file"
      - "traefik.http.services.roadmap-for-bjj.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
