source_directories:
  - /source/data

exclude_patterns:
  - "*/borg"
  - "*/borgmatic"
  - "*/db.sqlite3*"

sqlite_databases:
  - name: authelia
    path: /source/data/db.sqlite3

repositories:
  - path: /repository
    label: authelia

archive_name_format: "authelia-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "authelia backup complete"
    message: "authelia backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "authelia backup FAILED"
    message: "authelia backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
