services:
  cyberchef:
    container_name: cyberchef
    image: ghcr.io/gchq/cyberchef:11.0.0@sha256:45082a0ac41d6beeea2daeb192d8b20c66520362854542f4fe340aab37635f66
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    init: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=Host(`cyberchef.jaw.dev`)"
      - "traefik.http.routers.cyberchef.entrypoints=websecure"
      - "traefik.http.routers.cyberchef.middlewares=google-auth@file"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
