postgresql_databases:
  - name: bitmagnet
    hostname: bitmagnet-db
    username: postgres
    format: custom

repositories:
  - path: /repository
    label: bitmagnet

archive_name_format: "bitmagnet-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "bitmagnet db backup complete"
    message: "bitmagnet database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "bitmagnet db backup FAILED"
    message: "bitmagnet database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
