source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/radarr.db*"
  - "*/logs.db*"
  - "*/asp"
  - "*/logs"
  - "*/Sentry"
  - "*.pid"

sqlite_databases:
  - name: radarr
    path: /source/data/radarr.db

repositories:
  - path: /repository
    label: radarr

archive_name_format: "radarr-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "radarr backup complete"
    message: "radarr backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "radarr backup FAILED"
    message: "radarr backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
