apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel
  namespace: network
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:MkFLh92zO8ShZmymQteeAE82khPGafJ0w6fJejG91ckRXufEw8SqGHNVZi4BEb1zO0i8I1L43YIT3iEGcmrZAggJsjK5qilddyVaxVzzVN43SIdn1BEj6ncFHxgbF67AryrKzQctiMUVDAtjsXy2M49E/0+3EwDiaCmQmVl+1lKOo1bbSnyY4hL9PP7b8GbEbheTO2VSM2W8Hw8Dym0YqK6NIws1WoMTrC24rwtQIHaBF88bFXOLYw==,iv:sUaCmd+1/R5p6JRWOvm3dHWxqIRqJhcPuI1ar+TpTpQ=,tag:xUpf8yZ3KVTzo4I8GI73Yw==,type:str]
sops:
  age:
    - recipient: age1jcnrthtt049n6e2w2hpyq8r342q97r3ws44m0maty4dx527yvd7qyucfnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMXpRSHROMXN6d0tSQWox
        c1YzRWxubkQrZkZkU3BKTU15dDdSMllVSkJvCk8yL0ZtZDY0bVNhUlZCYld2OVFU
        eGUyOXJHaDZHdWpwN1lya1RYQ2drK3cKLS0tIFhtMXBvNzZrckxqUEI3SWdrWmtH
        SFBWVmZpMm0zMVRRVk9oc0ZWWEN3VGcKQHr8YbDCzCA74Iwfj7+ribYFkbXum3zq
        9kggp0dOg8onghkY7UXPovRh+u2PF0NDb8BZk04kjW3UGAjLxoxWrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T02:31:31Z"
  mac: ENC[AES256_GCM,data:UwB4SzOlHgUiPFa8HwdX+TR8QnMNk9dCfhdjxGMZHuXN86OR6tC3o7YJkGRQ2ZxrQR0TFiEcdssHydMA/CGqHSPwuUchmdKgpYIGVp2y2YW9902yEnmrtYUKTBEoPqe88XJXQgcDz2E6dQCEmzQUp6sXxtUMYdwOYXHa3ji8nus=,iv:Rw1Wh2ZGUjbNXjGiCZeL2solgEHZ4rMvA9wbgWKBmuc=,tag:qcekVV0DFxz/aFJ55TAgzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
