apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:Yc0uYsBrMyw6mmBisn5AUiOBJTSP4eWMh3APhZhDBp2xBBzGxMMH/g==,iv:nIZonyGTaSMDuDMHWsENex75DFKF/j7NJ14yhAqh7wo=,tag:XRI7V2tahyfclpbNf1yTbA==,type:str]
sops:
  age:
    - recipient: age1jcnrthtt049n6e2w2hpyq8r342q97r3ws44m0maty4dx527yvd7qyucfnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6THJpVUhUNFZybDgvYmN3
        ZHVRTTV6a2xTOXFJNVJKZ1NLdmw2ZGx4QUdJCmJEV09SSFR6d0IwQTlWd05aS0U3
        S05qSlNHNFdObnppL1RCamttVzlIUVUKLS0tIDVCd0pUT0RBWWJVZ0h2TWNvL2tO
        Zm1kYUl2M0ordjlqUm8ya2U0eU9heDgKIRY5/TLhxuakTxOFIxj/GZZ13Z64zsPH
        87P3yDYTvP0kib1jIWLXyJ+uUQtYwnsGuxIubPMCPRcYgCgrOV7Slg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T02:20:11Z"
  mac: ENC[AES256_GCM,data:HnOrMR4LCwvsQFb8MwbB3dAieC62Ky9WU3V0f623gQccqK036EpKP53xNGDKQaTTCj39xJJHlBUDbOPYCrNlmTWO/CCNvvAL8tnirNfVdFgulJAhZjh6e62GwCPfD0TqZETtpZbhyrGQVqtcJDxOCx/MXZXNnKvKsarieeyMVyE=,iv:PSlxYN+Upsjb5zDbv1W0/YUzqXu0Q5mpUrF4wEjsZxk=,tag:rEBtPNqY0BtNXMmhd7u9Sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
