sqlite_databases:
  - name: mm2us
    path: /source/data/db.sqlite

repositories:
  - path: /repository
    label: mm2us

archive_name_format: "mm2us-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "mm2us db backup complete"
    message: "mm2us database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "mm2us db backup FAILED"
    message: "mm2us database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
