sqlite_databases:
  - name: gains
    path: /source/data/db.sqlite

repositories:
  - path: /repository
    label: gains

archive_name_format: "gains-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "gains db backup complete"
    message: "gains database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "gains db backup FAILED"
    message: "gains database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
