postgresql_databases:
  - name: hello
    hostname: hello-world-db
    username: hello
    format: custom

repositories:
  - path: /repository
    label: hello-world

archive_name_format: "hello-world-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "hello-world db backup complete"
    message: "hello-world database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "hello-world db backup FAILED"
    message: "hello-world database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
