title: Home Ops
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/docker.png
color: slate
headerStyle: boxedWidgets
hideVersion: true
hideErrors: true
showStats: false
cardBlur: sm
statusStyle: dot
iconStyle: theme
fullWidth: true
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
layout:
  Media:
    style: column
    tab: Media
  Downloaders:
    style: column
    tab: Media
  Systems:
    style: column
    tab: Infra
  Logs:
    style: column
    tab: Infra
  Personal:
    style: column
    tab: Apps
  Tools:
    style: column
    tab: Apps
  Dev:
    style: column
    tab: Apps
