source_directories:
  - /source/data

exclude_patterns:
  - "*/borg"
  - "*/borgmatic"
  - "*/prowlarr.db*"
  - "*/logs.db*"

sqlite_databases:
  - name: prowlarr
    path: /source/data/prowlarr.db

repositories:
  - path: /repository
    label: prowlarr

archive_name_format: "prowlarr-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "prowlarr backup complete"
    message: "prowlarr backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "prowlarr backup FAILED"
    message: "prowlarr backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
