source_directories:
  - /source/data

exclude_patterns:
  - "*/borg"
  - "*/borgmatic"
  - "*/db.sqlite*"

sqlite_databases:
  - name: favicon
    path: /source/data/db.sqlite

repositories:
  - path: /repository
    label: favicon

archive_name_format: "favicon-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "favicon backup complete"
    message: "favicon backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "favicon backup FAILED"
    message: "favicon backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
