source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/listenarr.db*"
  - "*/ffmpeg"

sqlite_databases:
  - name: listenarr
    path: /source/data/database/listenarr.db

repositories:
  - path: /repository
    label: nas
  - path: /local-backup
    label: local

archive_name_format: "listenarr-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "listenarr backup complete"
    message: "listenarr backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "listenarr backup FAILED"
    message: "listenarr backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
