source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/kuma.db*"

sqlite_databases:
  - name: uptime-kuma
    path: /source/data/kuma.db

repositories:
  - path: /repository
    label: uptime-kuma

archive_name_format: "uptime-kuma-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "uptime-kuma backup complete"
    message: "uptime-kuma backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "uptime-kuma backup FAILED"
    message: "uptime-kuma backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
