services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
    volumes:
      - /home/jaw/data/uptime-kuma:/app/data
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "node", "extra/healthcheck.js"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    init: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`status.jaw.dev`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.middlewares=google-auth@file"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
networks:
  traefik:
    external: true
