apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: prometheus
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:VjwkhXI=,iv:e5X4FoZC7MUdfJzzx6Dh0LcuxMp3RGYCBcO+wxcO0G4=,tag:3wFokU1yfXoarjfFxqvxXg==,type:str]
  admin-password: ENC[AES256_GCM,data:AbBnoYsbG7tXEZW06EYoIRg0p7Ey7o3PDvXLmA==,iv:1I1CV5L20hW0yRxsjnMcj/VUtNZy+waBPEOtxi5uZMA=,tag:o0/iR27NFiEP4XYHDkOjtQ==,type:str]
sops:
  age:
    - recipient: age1jcnrthtt049n6e2w2hpyq8r342q97r3ws44m0maty4dx527yvd7qyucfnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TS9wcmx3QjROMHVyNkQ3
        cW83aEhDUUZYQ3F2TzREK1FxcCtOS01mSVRnCisyZDJhU2xxODhBRkxNRTdOT1dV
        eFFySXpYQXVtR3I4RXMzNFNZbnRVU00KLS0tIE02U2ZKVEVMcGE1T2xhSTJMaG5R
        YlJ1RkxWTWlOM1VnSUZha3J0NFlBVkUKd0aA2LKg4y/Y+uaH4T12WT2HYQWZpcLA
        pGPlXK8HYBzq5iyWJ8+X0J8IQtDOJDrT6PzOafAu6a50SeUhRA114g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-19T20:13:49Z"
  mac: ENC[AES256_GCM,data:TazO/YxfaA9hFsR4YSawd7V/NxlPw1q9aAKG4JvQV92YNFaUBgfXH/QXJEEtM/BHZRT+794r6b83UYBK6No30or0gnvj5XGFJ/nfwpMw6de3hLRCaJVNKVs1ZD+oFwBGPtPrW129cRw1JT/XM0WErC+nC4Ri/rGAz6UGhBgMIBM=,iv:k8i1j3ap850OYkArHY8aM7V3nP+JSb2iDAbiW0l0EI4=,tag:ARPfvfbLbnmFU/lwgfEbRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
