source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/frigate.db*"
  - "*/media"
  - "*/model_cache"

sqlite_databases:
  - name: frigate
    path: /source/data/frigate.db

repositories:
  - path: /repository
    label: nas
  - path: /local-backup
    label: local

archive_name_format: "frigate-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "frigate backup complete"
    message: "frigate backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "frigate backup FAILED"
    message: "frigate backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
