auth:
  enabled: false

mqtt:
  enabled: true
  host: mosquitto
  port: 1883

database:
  path: /config/frigate.db

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

audio:
  enabled: true
  listen:
    - fire_alarm
    - scream
    - yell
    - glass_breaking

objects:
  track:
    - person
    # - dog
    # - cat
  filters:
    person:
      min_score: 0.5
      min_area: 1500

review:
  alerts:
    labels:
      - person

record:
  enabled: true
  retain:
    days: 7
    mode: motion

snapshots:
  enabled: true
  clean_copy: false
  retain:
    default: 7

go2rtc:
  api:
    origin: "*"
  webrtc:
    candidates:
      - 192.168.4.161:8555
  streams:
    tapo_cam:
      - rtsp://{FRIGATE_CAM_USER}:{FRIGATE_CAM_PASS}@{FRIGATE_CAM_IP}:554/stream1#backchannel=0
      - "ffmpeg:tapo_cam#video=h264#hardware=vaapi"
      - tapo://admin:{FRIGATE_TAPO_SHA256}@{FRIGATE_CAM_IP}

cameras:
  tapo_cam:
    enabled: true
    onvif:
      host: "{FRIGATE_CAM_IP}"
      port: 2020
      user: "{FRIGATE_CAM_USER}"
      password: "{FRIGATE_CAM_PASS}"
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_cam
          roles:
            - record
            - audio
        - path: rtsp://{FRIGATE_CAM_USER}:{FRIGATE_CAM_PASS}@{FRIGATE_CAM_IP}:554/stream2
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    motion:
      contour_area: 25
    objects:
      track:
        - person
        # - dog
        # - cat
    record:
      enabled: true
    snapshots:
      enabled: true
