source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/data.db*"

sqlite_databases:
  - name: beszel
    path: /source/data/data.db

repositories:
  - path: /repository
    label: nas

archive_name_format: "beszel-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "beszel backup complete"
    message: "beszel backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "beszel backup FAILED"
    message: "beszel backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
