source_directories:
  - /source/data

exclude_patterns:
  - "*/borg"
  - "*/borgmatic"
  - "*/absdatabase.sqlite*"

sqlite_databases:
  - name: audiobookshelf
    path: /source/data/config/absdatabase.sqlite

repositories:
  - path: /repository
    label: audiobookshelf

archive_name_format: "audiobookshelf-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "audiobookshelf backup complete"
    message: "audiobookshelf backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "audiobookshelf backup FAILED"
    message: "audiobookshelf backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
