postgresql_databases:
  - name: plausible
    hostname: plausible-db
    username: plausible
    format: custom

repositories:
  - path: /repository
    label: plausible

archive_name_format: "plausible-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "plausible db backup complete"
    message: "plausible database backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "plausible db backup FAILED"
    message: "plausible database backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
