source_directories:
  - /source/data

exclude_patterns:
  - "*/borgmatic"
  - "*/db"

postgresql_databases:
  - name: glitchtip
    hostname: glitchtip-db
    username: glitchtip
    format: custom

repositories:
  - path: /repository
    label: glitchtip

archive_name_format: "glitchtip-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "glitchtip backup complete"
    message: "glitchtip backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "glitchtip backup FAILED"
    message: "glitchtip backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
