---
clusterName: home-cluster
talosVersion: v1.12.6
kubernetesVersion: v1.35.2
endpoint: https://192.168.4.162:6443

nodes:
  - hostname: soapwa
    ipAddress: 192.168.4.162
    controlPlane: true
    installDisk: /dev/sdb

  - hostname: yanlon
    ipAddress: 192.168.4.163
    controlPlane: false
    installDisk: /dev/nvme0n1

  # - hostname: apollo
  #   ipAddress: 192.168.4.161
  #   controlPlane: false
  #   installDisk: /dev/nvme0n1

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/nut-client

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/nut-client
