apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudflared
  - cnpg
  - echo
  - hello-world
  - intel-gpu-plugin
  - kube-system
  - longhorn
  - nfs-backup
  - node-feature-discovery
  - prometheus
  - system-upgrade
  - volsync
