source_directories:
  - /source/data

exclude_patterns:
  - "*/borg"
  - "*/borgmatic"
  - "*/db"

postgresql_databases:
  - name: zipline
    hostname: zipline-db
    username: zipline
    format: custom

repositories:
  - path: /repository
    label: zipline

archive_name_format: "zipline-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "zipline backup complete"
    message: "zipline backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "zipline backup FAILED"
    message: "zipline backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
