source_directories:
  - /source/data
  - /source/sops

repositories:
  - path: /repository
    label: nas

archive_name_format: "{hostname}-{now:%Y-%m-%d-%H%M%S}"

compression: zstd,3

keep_daily: 30
keep_weekly: 12
keep_monthly: 12

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

postgresql_databases:
  - name: miniflux
    hostname: miniflux-db
    port: 5432
    username: miniflux
    password: ${MINIFLUX_DB_PASSWORD}
  - name: plausible
    hostname: plausible-db
    port: 5432
    username: plausible
    password: ${PLAUSIBLE_DB_PASSWORD}
  - name: zipline
    hostname: zipline-db
    port: 5432
    username: zipline
    password: ${ZIPLINE_DB_PASSWORD}
  - name: glitchtip
    hostname: glitchtip-db
    port: 5432
    username: glitchtip
    password: ${GLITCHTIP_DB_PASSWORD}
  - name: bitmagnet
    hostname: bitmagnet-db
    port: 5432
    username: postgres
    password: ${BITMAGNET_DB_PASSWORD}
  - name: hello
    hostname: hello-world-db
    port: 5432
    username: hello
    password: ${HELLO_DB_PASSWORD}
  - name: paperless
    hostname: paperless-db
    port: 5432
    username: paperless
    password: ${PAPERLESS_DB_PASSWORD}

sqlite_databases:
  - name: gitea
    path: /source/data/gitea/gitea/gitea.db
  - name: close-powerlifting
    path: /source/data/close-powerlifting/db.sqlite
  - name: bang
    path: /source/data/bang/db.sqlite
  - name: gains
    path: /source/data/gains/db.sqlite
  - name: mm2us
    path: /source/data/mm2us/db.sqlite
  - name: notify
    path: /source/data/notify/db.sqlite
  - name: calendar
    path: /source/data/calendar/db.sqlite
  - name: favicon
    path: /source/data/favicon/db.sqlite
  - name: screenshot
    path: /source/data/screenshot/db.sqlite

commands:
  - after: everything
    run:
      - wget -qO /dev/null "${UPTIME_KUMA_PUSH_URL}"

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: Backup complete
    message: Borgmatic backup finished successfully
    priority: min
    tags: white_check_mark
  fail:
    title: Backup FAILED
    message: Borgmatic backup has failed
    priority: max
    tags: skull
  states:
    - finish
    - fail
