services:
  borgmatic:
    container_name: borgmatic
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.5@sha256:f6b0a640d72bf7bb628479246e7c919404917cc58ddc6cdfb8d2d40d786d3a26
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    volumes:
      - /home/jaw/data:/source/data:ro
      - /home/jaw/.sops:/source/sops:ro
      - /home/jaw/backup/borg:/repository
      - /home/jaw/data/borgmatic:/borgmatic/state
      - ./config.yml:/etc/borgmatic/config.yaml:ro
      - ./crontab.txt:/etc/borgmatic.d/crontab.txt:ro # force
    networks:
      - backup
      - traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "borgmatic --version"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_drop:
      - ALL
    cap_add:
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

networks:
  traefik:
    external: true
  backup:
    external: true
