services:
  borgmatic:
    container_name: borgmatic
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.3@sha256:529ef5f19838b650e07de2cdf91e0f403d849cf83636baacc6ec8a55e2a76f79
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    volumes:
      - /home/jaw/data:/source/data:ro
      - /home/jaw/.sops:/source/sops:ro
      - /home/jaw/backup/borg:/repository
      - /home/jaw/data/borgmatic:/borgmatic/state
      - ./config.yml:/etc/borgmatic/config.yaml:ro
      - ./crontab.txt:/etc/borgmatic.d/crontab.txt:ro # force
    networks:
      - traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "borgmatic --version"]
      interval: 1m
      timeout: 10s
      retries: 3
    cap_drop:
      - ALL
    cap_add:
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

networks:
  traefik:
    external: true
