---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  namespace: flux-system
spec:
  targetNamespace: hello-world
  interval: 30m
  path: ./kubernetes/apps/hello-world/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cnpg
    - name: cilium-gateway
  wait: true
  timeout: 5m
