bind = 0.0.0.0:8080
sitename = linx.jaw.dev
siteurl = https://linx.jaw.dev/
s3-endpoint = http://garage:3900
s3-region = garage
s3-bucket = linx
s3-force-path-style = true
maxsize = 104857600
maxexpiry = 2592000
allowhotlink = true
realip = true
force-random-filename = true
nodirectagents = true
