source_directories:
  - /source/data

exclude_patterns:
  - "*/borg"
  - "*/borgmatic"
  - "*/gitea/gitea.db*"

sqlite_databases:
  - name: gitea
    path: /source/data/gitea/gitea.db

repositories:
  - path: /repository
    label: gitea

archive_name_format: "gitea-{now:%Y-%m-%d-%H%M%S}"
compression: zstd,3

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

check_last: 3

ntfy:
  topic: borgmatic
  server: http://ntfy:80
  finish:
    title: "gitea backup complete"
    message: "gitea backup finished"
    priority: min
    tags: white_check_mark
  fail:
    title: "gitea backup FAILED"
    message: "gitea backup failed"
    priority: max
    tags: skull
  states:
    - finish
    - fail
